["Dans quel département se trouve Châlons-en-Champagne ?",1,["Ardennes","Marne","Aube","Meuse"],"B"],
["Quelle rivière traverse Châlons-en-Champagne ?",0,null,"La Marne"],
["Quel est le nom de la grande place devant l'Hôtel de Ville ?",1,["Place Foch","Place de Verdun","Place de la République","Place Monseigneur Tissier"],"A"],
["Quel grand bâtiment religieux domine le centre-ville ?",0,null,"La cathédrale Saint-Étienne"],
["Quel est le nom de la cathédrale de Châlons ?",1,["Notre-Dame","Saint-Alpin","Saint-Étienne","Saint-Loup"],"C"],
["Quel est le nom de la collégiale située dans le centre historique ?",0,null,"Notre-Dame-en-Vaux"],
["Quel grand espace vert se trouve au cœur de la ville ?",1,["Le Grand Jard","Le Parc Lavoisier","Le Parc Charcot","Le Parc de Champagne"],"A"],
["Combien de Jards principaux trouve-t-on à Châlons ?",0,null,"Trois"],
["Lequel de ces noms correspond à un Jard de Châlons ?",1,["Grand Jard","Jard Foch","Jard de la Marne","Jard Central"],"A"],
["Cite les trois Jards de Châlons.",0,null,"Petit Jard, Grand Jard et Jard anglais"],
["Quel lieu permet de prendre le train à Châlons ?",1,["La gare","La Comète","La préfecture","Le Grand Jard"],"A"],
["Quel moyen de transport trouve-t-on à la gare ?",0,null,"Le train"],
["Châlons possède-t-elle un réseau de bus ?",1,["Oui","Non","Seulement l'été","Seulement le dimanche"],"A"],
["Comment s'appelle le réseau de transports en commun de Châlons ?",0,null,"SITAC"],
["Quel grand bâtiment administratif représente l'État dans la Marne ?",1,["La mairie","La préfecture","La gare","Le tribunal"],"B"],
["Châlons est-elle la préfecture de la Marne ?",0,null,"Oui"],
["Où se trouve l'Hôtel de Ville ?",1,["Place Foch","Place de Verdun","Grand Jard","Avenue de Paris"],"A"],
["Quelle grande ville est située au nord-ouest de Châlons ?",0,null,"Reims"],
["Quel transport permet notamment de rejoindre Paris depuis Châlons ?",1,["Le métro","Le train","Le tramway","Le bateau"],"B"],
["Châlons possède-t-elle un centre-ville historique ?",0,null,"Oui"],
["Quel endroit est particulièrement connu pour ses promenades ?",1,["Les Jards","La zone industrielle","La gare","Croix-Dampierre"],"A"],
["Quel monument possède un célèbre carillon ?",0,null,"Notre-Dame-en-Vaux"],
["Quel lieu accueille de nombreux spectacles à Châlons ?",1,["La Comète","La Préfecture","La Gare","Le Tribunal"],"A"],
["Quel est le nom de la scène nationale de Châlons ?",0,null,"La Comète"],
["Quel lieu est adapté pour voir un spectacle ?",1,["La Comète","La préfecture","La gare","Le cimetière"],"A"],
["Quel type d'équipement est le Capitole en Champagne ?",0,null,"Un parc des expositions / équipement événementiel"],
["Quel type d'établissement est un collège ?",1,["Un établissement scolaire","Un hôpital","Un musée","Une mairie"],"A"],
["Quel type d'établissement est un lycée ?",0,null,"Un établissement scolaire"],
["Peut-on trouver un hôpital à Châlons ?",1,["Oui","Non","Seulement à Reims","Seulement à Saint-Memmie"],"A"],
["Peut-on trouver une caserne de pompiers à Châlons ?",0,null,"Oui"],
["Châlons possède-t-elle une police municipale ?",1,["Oui","Non","Seulement la nuit","Seulement l'été"],"A"],
["Cite un quartier de Châlons.",0,null,"libre"],
["Châlons possède-t-elle des zones commerciales en périphérie ?",1,["Oui","Non","Une seule petite boutique","Seulement dans le centre"],"A"],
["Quel endroit est généralement plus animé : le centre-ville ou une zone industrielle ?",0,null,"Le centre-ville"],
["Quel transport roule sur la route et prend plusieurs passagers ?",1,["Le train","Le bus","Le bateau","Le vélo"],"B"],
["Où attend-on généralement un bus ?",0,null,"À un arrêt de bus"],
["Que peut-on généralement trouver sur une grande place ?",1,["Des commerces et bâtiments publics","Une autoroute","Une piste d'aéroport","Une voie ferrée principale"],"A"],
["Quel type de voie permet de circuler rapidement entre deux secteurs de la ville ?",0,null,"Un grand axe routier"],
["Châlons possède-t-elle beaucoup d'espaces verts ?",1,["Oui","Non","Seulement en dehors de la ville","Seulement autour de la gare"],"A"],
["Quel lieu choisirais-tu pour une promenade tranquille au centre de Châlons ?",0,null,"Les Jards"],
["Lequel est un des trois Jards ?",1,["Jard anglais","Jard Foch","Jard République","Jard Saint-Martin"],"A"],
["Quel Jard est le plus grand ?",0,null,"Le Grand Jard"],
["Quel Jard possède un skatepark à proximité ?",1,["Grand Jard","Petit Jard","Jard anglais","Aucun"],"A"],
["Quel espace vert est relié au Grand Jard par une passerelle ?",0,null,"Le Jard anglais"],
["Où se déroule notamment Châlons Plage ?",1,["Au Grand Jard","À la gare","À Croix-Dampierre","Au Verbeau uniquement"],"A"],
["Cite une activité que l'on peut retrouver à Châlons Plage.",0,null,"libre"],
["Quel équipement sportif se trouve au Grand Jard ?",1,["Un terrain de football","Une piscine olympique","Un stade de rugby professionnel","Une patinoire"],"A"],
["Quel type d'équipement trouve-t-on à proximité de l'avenue du Maréchal Leclerc au Grand Jard ?",0,null,"Un skatepark"],
["Quel quartier possède des terrains de football et de basket rue Georges Barbier ?",1,["Verbeau","Schmit","Bidée","Mont-Héry"],"A"],
["Quel quartier est associé au CSC Émile Schmit ?",0,null,"Le quartier Schmit"],
["Quel quartier est associé à la rue Georges Barbier ?",1,["Verbeau","Schmit","Mont-Héry","Vallée-Saint-Pierre"],"A"],
["Quel équipement sportif trouve-t-on au stade Mermoz ?",0,null,"Une piste d'athlétisme et un terrain de basket"],
["Dans quel quartier se trouve un terrain multisports rue J.S. Bach ?",1,["Vallée-Saint-Pierre","Schmit","Verbeau","Bidée"],"A"],
["Dans quel quartier trouve-t-on un terrain multisports rue Branly ?",0,null,"Schmit"],
["Où trouve-t-on des terrains de basket et de football à l'Aire des Grévières ?",1,["Avenue Croix-Dampierre","Place Foch","Rue de la Marne","Avenue de Paris"],"A"],
["Quel quartier possède un terrain de football à côté du CSC Rive Gauche ?",0,null,"La Bidée"],
["Quel équipement se trouve avenue Pierre Semard ?",1,["Un terrain multisports","Une cathédrale","Une patinoire","Un musée"],"A"],
["Quel équipement sportif trouve-t-on à Mont-Saint-Michel ?",0,null,"Un terrain de basket"],
["Où trouve-t-on des terrains de basket et un terrain de football synthétique ?",1,["Mont-Héry","Verbeau","Schmit","Grand Jard"],"A"],
["Quel équipement sportif se trouve au Pont Vert ?",0,null,"Des terrains de basket, handball, football, tennis et bicross"],
["Quel lieu accueille une piscine à Châlons ?",1,["Aquacité","La Comète","Le Capitole","La Duduchothèque"],"A"],
["Combien de piscines composent le pôle aquatique de l'agglomération ?",0,null,"Trois"],
["Que peut-on trouver à Aquacité ?",1,["Un bassin sportif de 25 m","Une gare","Une patinoire extérieure","Un terrain de football"],"A"],
["Combien de lignes d'eau possède le bassin sportif d'Aquacité ?",0,null,"Six"],
["Quel équipement peut-on trouver à Aquacité ?",1,["Un espace bien-être","Une piste d'athlétisme","Une salle de cinéma","Un skatepark"],"A"],
["Cite une activité aquatique que l'on peut pratiquer à Aquacité.",0,null,"libre"],
["Quel lieu est associé au patinage ?",1,["Cité Glace","La Comète","Aquacité","Le Grand Jard"],"A"],
["Quel équipement permet de pratiquer le patinage à Châlons ?",0,null,"Cité Glace"],
["Quel lieu est associé aux arts du cirque ?",1,["CNAC","SITAC","Aquacité","Cité Glace"],"A"],
["Que signifie CNAC ?",0,null,"Centre National des Arts du Cirque"],
["Quel lieu accueille notamment les activités du CNAC ?",1,["La Marnaise","La Préfecture","La gare","Le Petit Jard"],"A"],
["Dans quelle avenue se trouve La Marnaise ?",0,null,"Avenue du Maréchal Leclerc"],
["Quel équipement culturel peut accueillir du cinéma, du spectacle et des événements ?",1,["La Comète","La mairie","Le stade Mermoz","La gare"],"A"],
["Quel festival est notamment associé à La Comète ?",0,null,"War on Screen"],
["Quel lieu permet de découvrir des collections et œuvres ?",1,["Un musée","Une gare","Un gymnase","Une piscine"],"A"],
["Cite un musée de Châlons-en-Champagne.",0,null,"libre"],
["Quel lieu est consacré notamment à René Georges Hermann Paul ?",1,["La Duduchothèque","Aquacité","La Comète","Cité Glace"],"A"],
["Quel célèbre dessinateur est associé à la Duduchothèque ?",0,null,"Cabu"],
["Quel lieu permet de découvrir le patrimoine de Châlons ?",1,["Le CIAP","Le stade Mermoz","La gare","Aquacité"],"A"],
["Que signifie CIAP ?",0,null,"Centre d'Interprétation de l'Architecture et du Patrimoine"],
["Où se trouve la Médiathèque Pompidou ?",1,["Dans le centre de Châlons","Au Grand Jard","Dans une zone industrielle","À Fagnières uniquement"],"A"],
["Quel type de documents peut-on notamment trouver dans une médiathèque ?",0,null,"libre"],
["Quel lieu est associé à l'innovation et à la fabrication numérique ?",1,["L'OctoLab","La Préfecture","Cité Glace","Le Grand Jard"],"A"],
["Quel est le rôle général d'un FabLab comme l'OctoLab ?",0,null,"Permettre d'expérimenter, fabriquer, apprendre et créer"],
["Quel équipement est associé à la musique et à la danse ?",1,["Conservatoire Jean-Philippe Rameau","Cité Glace","Aquacité","Capitole"],"A"],
["Quel est le nom du conservatoire de Châlons ?",0,null,"Conservatoire Jean-Philippe Rameau"],
["Quel lieu est adapté à une sortie nature dans l'agglomération ?",1,["Domaine de Coolus","La gare","La préfecture","La zone commerciale"],"A"],
["Quel domaine naturel proche de Châlons peut-on visiter ?",0,null,"Le Domaine de Coolus"],
["Quel lieu peut accueillir un grand événement ou salon ?",1,["Le Capitole en Champagne","Le Petit Jard uniquement","La cathédrale","La gare"],"A"],
["Quel type d'événements peut accueillir le Capitole ?",0,null,"libre"],
["Quel équipement est principalement destiné aux spectacles ?",1,["La Comète","La préfecture","Le tribunal","Aquacité"],"A"],
["Quel équipement est principalement destiné à la baignade et aux activités aquatiques ?",0,null,"Aquacité"],
["Quel équipement est principalement destiné au patinage ?",1,["Cité Glace","La Comète","Le CNAC","Le Grand Jard"],"A"],
["Quel équipement est principalement destiné aux arts du cirque ?",0,null,"Le CNAC"],
["Quel espace est principalement destiné à la promenade et aux loisirs extérieurs ?",1,["Les Jards","La préfecture","La gare","Le tribunal"],"A"],
["Cite un équipement sportif en accès libre à Châlons.",0,null,"libre"],
["Quel quartier possède un terrain multisports rue J.S. Bach ?",1,["Vallée-Saint-Pierre","Schmit","Verbeau","Bidée"],"A"],
["Quel quartier possède un terrain multisports rue Branly ?",0,null,"Schmit"],
["Quel quartier possède des terrains de football et de basket rue Georges Barbier ?",1,["Verbeau","Mont-Héry","Schmit","Vallée-Saint-Pierre"],"A"],
["Quel équipement trouve-t-on rue du Camp d'Attila ?",0,null,"Le stade Mermoz"],
["Quel équipement trouve-t-on au Stade Mermoz ?",1,["Piste d'athlétisme et terrain de basket","Piscine et patinoire","Skatepark et tennis","Terrain de rugby uniquement"],"A"],
["Dans quelle rue se trouve le stade Mermoz ?",0,null,"Rue du Camp d'Attila"],
["Quel quartier possède un terrain de football à proximité du CSC Rive Gauche ?",1,["Bidée","Schmit","Verbeau","Mont-Héry"],"A"],
["Quel quartier est associé au CSC Schmit ?",0,null,"Schmit"],
["Quel secteur est rattaché au territoire d'influence du CSC Schmit ?",1,["Mont-Héry","Centre-ville uniquement","Gare uniquement","Croix-Dampierre uniquement"],"A"],
["Cite un autre quartier rattaché au territoire d'influence du CSC Schmit.",0,null,"libre"],
["Le CSC Schmit est principalement un lieu :",1,["Social, culturel et de proximité","Judiciaire","Ferroviaire","Commercial"],"A"],
["Dans quel quartier est implanté le CSC Émile Schmit ?",0,null,"Schmit"],
["Quel équipement sportif est situé rue Branly ?",1,["Un terrain multisports","Une piscine","Une patinoire","Un stade de football professionnel"],"A"],
["Quel équipement sportif est situé rue J.S. Bach ?",0,null,"Un terrain multisports"],
["Quel équipement se trouve avenue Croix-Dampierre ?",1,["Aire des Grévières","Cité Glace","La Comète","Le CIAP"],"A"],
["Quels sports peut-on pratiquer librement à l'Aire des Grévières ?",0,null,"Basket et football"],
["Quel équipement trouve-t-on avenue Pierre Semard ?",1,["Espace Pierre Semard","Hôtel de Ville","Cathédrale","Capitole"],"A"],
["Quel type de terrain trouve-t-on à l'Espace Pierre Semard ?",0,null,"Un terrain multisports"],
["Quel équipement trouve-t-on au Mont-Saint-Michel ?",1,["Terrain de basket","Piscine","Tennis couvert","Stade de football"],"A"],
["Quel équipement trouve-t-on au quartier Mont-Héry ?",0,null,"Terrains de basket et terrain de football synthétique"],
["Quel quartier possède des terrains de basket et un terrain de football synthétique rue J.B. Drouet ?",1,["Mont-Héry","Schmit","Verbeau","Bidée"],"A"],
["Quelle rue dessert l'équipement sportif de Mont-Héry ?",0,null,"Rue J.B. Drouet"],
["Quel équipement possède des terrains de football, handball, tennis et bicross ?",1,["Pont Vert","Grand Jard","Verbeau","Mont-Héry"],"A"],
["Où se trouve le site sportif du Pont Vert ?",0,null,"Allées de Forêts"],
["Quel équipement trouve-t-on au Grand Jard ?",1,["Terrain de football","Terrain de baseball","Piscine","Stade couvert"],"A"],
["Sur quelle avenue se trouve le terrain sportif du Grand Jard ?",0,null,"Avenue du Général Leclerc"],
["Quel équipement trouve-t-on à proximité de l'avenue du Maréchal Leclerc au Grand Jard ?",1,["Skatepark","Piscine","Patinoire","Gare routière"],"A"],
["Quel type d'activités peut-on retrouver au Grand Jard pendant Châlons Plage ?",0,null,"libre"],
["Quel lieu est directement bordé par un canal ?",1,["Grand Jard","Stade Mermoz","Verbeau","Croix-Dampierre"],"A"],
["Quel Jard est séparé par le canal latéral à la Marne ?",0,null,"Le Jard anglais"],
["Quel Jard est connu pour son arboretum ?",1,["Petit Jard","Grand Jard","Jard anglais","Aucun"],"A"],
["Environ combien d'espèces d'arbres et d'arbustes sont présentes dans l'arboretum du Petit Jard ?",0,null,"Environ 200"],
["Quel espace possède un kiosque à musique central ?",1,["Grand Jard","Verbeau","Petit Jard uniquement","Croix-Dampierre"],"A"],
["Quel est le point central du Grand Jard ?",0,null,"Le kiosque à musique"],
["Quel lieu est surnommé l'un des poumons verts de Châlons ?",1,["Les Jards","La gare","La zone commerciale","Le tribunal"],"A"],
["Combien de Jards sont ouverts au public au centre-ville ?",0,null,"Trois"],
["Lequel de ces lieux n'est PAS un Jard ?",1,["Jard anglais","Petit Jard","Grand Jard","Jard Foch"],"D"],
["Quel espace vert possède un style de jardin paysager ?",0,null,"Le Petit Jard"],
["Quel lieu est le plus adapté pour faire du skate ?",1,["Le skatepark du Grand Jard","La préfecture","La gare","Le musée"],"A"],
["Quel lieu est adapté pour faire du bicross parmi les équipements sportifs libres d'accès ?",0,null,"Le site du Pont Vert"],
["Où peut-on trouver un terrain multisports dans le quartier Vallée-Saint-Pierre ?",1,["Rue J.S. Bach","Rue Branly","Rue Georges Barbier","Rue du Camp d'Attila"],"A"],
["Où peut-on trouver un terrain multisports dans le quartier Schmit ?",0,null,"Rue Branly"],
["Où peut-on trouver des terrains de football et basket dans le quartier Verbeau ?",1,["Rue Georges Barbier","Rue J.S. Bach","Rue Branly","Rue J.B. Drouet"],"A"],
["Quel équipement sportif trouve-t-on rue du Camp d'Attila ?",0,null,"Stade Mermoz"],
["Quel lieu est associé au tennis dans les équipements sportifs libres d'accès ?",1,["Pont Vert","Grand Jard","Verbeau","Mont-Saint-Michel"],"A"],
["Cite deux sports possibles au Pont Vert.",0,null,"libre"],
["Quel site propose notamment basket et football ?",1,["Aire des Grévières","Grand Jard","Cité Glace","La Comète"],"A"],
["Quel quartier possède un terrain de football à côté du CSC Rive Gauche ?",0,null,"Bidée"],
["Quel équipement trouve-t-on au quartier de la Bidée ?",1,["Terrain de football","Patinoire","Piscine","Piste d'athlétisme"],"A"],
["Quel équipement sportif trouve-t-on au Mont-Saint-Michel ?",0,null,"Terrain de basket"],
["Quel équipement est associé à l'athlétisme ?",1,["Stade Mermoz","Grand Jard","Pont Vert","Schmit"],"A"],
["Quel quartier possède un terrain multisports rue J.S. Bach ?",0,null,"Vallée-Saint-Pierre"],
["Quel quartier possède un terrain multisports rue Branly ?",1,["Schmit","Verbeau","Bidée","Mont-Héry"],"A"],
["Quel quartier possède des terrains de basket et de football rue Georges Barbier ?",0,null,"Verbeau"],
