["Tu es au Grand Jard et tu veux trouver un espace de glisse. Que cherches-tu ?",1,["Skatepark","Cité Glace","Aquacité","Stade Mermoz"],"A"],
["Quel type de séparation naturelle/artificielle trouve-t-on entre certains espaces des Jards ?",0,null,"libre"],
["Tu es dans le secteur Verbeau et tu cherches un terrain multisports. Quelle rue est une piste logique ?",1,["Georges Barbier","Branly","J.S. Bach","Oradour"],"A"],
["Tu es à Schmit et tu veux un terrain multisports : quelle rue dois-tu connaître ?",0,null,"Branly"],
["Tu es à Vallée-Saint-Pierre et tu veux un terrain multisports : quelle rue ?",1,["J.S. Bach","Georges Barbier","J.B. Drouet","Leconte de l'Isle"],"A"],
["Tu es à Mont-Héry et cherches un terrain de football synthétique : quelle rue ?",0,null,"J.B. Drouet"],
["Quel site est le meilleur choix si tu veux réunir football, tennis et bicross au même endroit ?",1,["Pont Vert","Mont-Saint-Michel","Aire des Grévières","Verbeau"],"A"],
["Cite trois sports disponibles au Pont Vert.",0,null,"libre"],
["Quel site est spécifiquement adapté au basket et football ?",1,["Aire des Grévières","Cité Glace","Aquacité","Petit Jard"],"A"],
["Où se trouve l'Aire des Grévières ?",0,null,"Avenue Croix-Dampierre"],
["Quel lieu est associé au terrain de football près du CSC Rive Gauche ?",1,["Bidée","Verbeau","Schmit","Mont-Héry"],"A"],
["Quel centre social est associé à la Bidée ?",0,null,"CSC Rive Gauche"],
["Quel centre social est associé au quartier Schmit ?",1,["CSC Émile Schmit","CSC Rive Gauche","CSC Verbeau","CSC Mermoz"],"A"],
["Quel centre social est associé à la Bidée ?",0,null,"CSC Rive Gauche"],
["Quel équipement sportif porte le nom de Mermoz ?",1,["Stade","Piscine","Patinoire","Skatepark"],"A"],
["Quel type d'activité sportive est particulièrement associé au stade Mermoz ?",0,null,"libre"],
["Quel lieu est situé avenue des Alliés ?",1,["Complexe sportif René Saché","Cité Glace","CIAP","Petit Jard"],"A"],
["Quel nom porte le complexe sportif avenue des Alliés ?",0,null,"René Saché"],
["Quel gymnase est associé au badminton dans le programme sportif ?",1,["Kiezer","Pierre Curie","Prieur de la Marne","Nicolas Appert"],"A"],
["Quel sport est associé au gymnase Kiezer dans le programme évoqué ?",0,null,"Badminton"],
["Quel gymnase est associé au foot en salle ?",1,["Pierre Curie","Kiezer","Prieur de la Marne","Nicolas Appert"],"A"],
["Où se trouve le gymnase Pierre Curie ?",0,null,"Rue Oradour"],
["Quel gymnase est associé à la danse classique/contemporaine ?",1,["Prieur de la Marne","Pierre Curie","Kiezer","Mermoz"],"A"],
["Dans quelle rue se trouve le gymnase Prieur de la Marne ?",0,null,"Rue du Grenier à Sel"],
["Quel lieu est utilisé pour le tennis de table ?",1,["Salle Cité Tirlet","Grand Jard","Stade Mermoz","Aquacité"],"A"],
["Dans quelle rue se trouve la Salle Cité Tirlet ?",0,null,"Rue de la Charrière"],
["Quel équipement est associé à la danse Hip-Hop dans le programme ?",1,["Dojo de la Trussonnerie","Stade Mermoz","Aquacité","Cité Glace"],"A"],
["Quelle rue est associée au dojo cité pour la danse Hip-Hop ?",0,null,"Rue Leconte de l'Isle"],
["Quel gymnase est associé aux activités de cirque ?",1,["Nicolas Appert","Pierre Curie","Kiezer","Prieur de la Marne"],"A"],
["Quel équipement est cité pour l'activité cirque ?",0,null,"Gymnase Nicolas Appert"],
["Quel lieu est associé à la danse Hip-Hop ?",1,["Dojo de la Trussonnerie","Cité Tirlet","Kiezer","Pierre Curie"],"A"],
["Quel sport/activité est associé à la Salle Cité Tirlet ?",0,null,"Tennis de table"],
["Quel sport est associé au complexe René Saché dans les activités citées ?",1,["Tennis","Natation","Patinage","Athlétisme uniquement"],"A"],
["Quel équipement porte le nom de René Saché ?",0,null,"Complexe sportif"],
["Quel équipement possède des terrains intérieurs et extérieurs de tennis ?",1,["Complexe René Saché","Stade Mermoz","Pont Vert","Grand Jard"],"A"],
["Sur quelle avenue sont annoncés les terrains de tennis du complexe René Saché ?",0,null,"Avenue des Alliés"],
["Tu veux du foot en salle : quel lieu est le plus pertinent parmi ces choix ?",1,["Gymnase Pierre Curie","Cité Glace","Aquacité","Petit Jard"],"A"],
["Tu veux du tennis de table : où vas-tu ?",0,null,"Salle Cité Tirlet"],
["Tu veux du badminton : quel lieu dois-tu retenir ?",1,["Gymnase Kiezer","Gymnase Pierre Curie","Grand Jard","Stade Mermoz"],"A"],
["Tu veux de la danse contemporaine : quel gymnase connais-tu ?",0,null,"Gymnase Prieur de la Marne"],
["Tu veux pratiquer le cirque : quel gymnase est cité ?",1,["Nicolas Appert","Kiezer","Pierre Curie","René Saché"],"A"],
["Quel lieu est associé aux arts du cirque à l'échelle nationale ?",0,null,"CNAC"],
["Tu cherches un lieu culturel associé à Cabu.",1,["Duduchothèque","Cité Tirlet","Aquacité","Pont Vert"],"A"],
["Quel lieu culturel est directement lié au patrimoine architectural de la ville ?",0,null,"CIAP"],
["Tu veux découvrir les collections des musées municipaux. Quel choix est logique ?",1,["Musée des Beaux-Arts et d'Archéologie","Stade Mermoz","Cité Glace","Aquacité"],"A"],
["Cite un autre musée de Châlons que le Musée des Beaux-Arts.",0,null,"Musée Garinet"],
["Quel lieu est particulièrement adapté à une exposition liée à Cabu ?",1,["Duduchothèque","Stade Mermoz","Pont Vert","Gare"],"A"],
["Quel équipement culturel porte le nom de Jean-Philippe Rameau ?",0,null,"Conservatoire"],
["Quel type d'activités se pratique au Conservatoire Jean-Philippe Rameau ?",1,["Musique et danse","Football","Natation","Patinage"],"A"],
["Cite deux disciplines que l'on peut associer au conservatoire.",0,null,"libre"],
["Tu dois faire une journée sportive avec trois activités différentes. Quel itinéraire est le plus cohérent ?",1,["Pont Vert → Aquacité → Cité Glace","Préfecture → cathédrale → mairie uniquement","Gare → musée → préfecture uniquement","CIAP → mairie → tribunal uniquement"],"A"],
["Donne trois lieux sportifs différents de Châlons qui ne sont pas dans le même secteur.",0,null,"libre"],
["Quel enchaînement associe correctement lieu et activité ?",1,["Cité Glace → patinage","Aquacité → cirque","CNAC → natation","Comète → football"],"A"],
["Associe trois lieux châlonnais à leur activité principale.",0,null,"libre"],
["Lequel de ces couples est incorrect ?",1,["Pont Vert → bicross","Grand Jard → skatepark","Cité Glace → natation","Aquacité → activités aquatiques"],"C"],
["Quel équipement choisirais-tu pour une personne qui veut pratiquer à la fois tennis et bicross ?",0,null,"Pont Vert"],
["Quel endroit réunit football, handball, tennis et bicross ?",1,["Pont Vert","Verbeau","Mont-Saint-Michel","Aire des Grévières"],"A"],
["Cite quatre sports différents que tu peux associer au Pont Vert.",0,null,"libre"],
["Quel équipement associe le plus clairement football + basket dans le secteur Verbeau ?",1,["Rue Georges Barbier","Rue Branly","Rue J.S. Bach","Rue Oradour"],"A"],
["Quel quartier associes-tu à Georges Barbier ?",0,null,"Verbeau"],
["Quel trio rue/quartier/équipement est correct ?",1,["Branly / Schmit / terrain multisports","Branly / Verbeau / piscine","J.S. Bach / Schmit / patinoire","Georges Barbier / Mont-Héry / tennis"],"A"],
["Donne le trio correspondant à J.S. Bach : quartier + équipement.",0,null,"Vallée-Saint-Pierre + terrain multisports"],
["Quel trio est correct ?",1,["J.B. Drouet / Mont-Héry / football synthétique","J.B. Drouet / Schmit / piscine","Oradour / Mont-Héry / tennis","Branly / Mont-Héry / patinage"],"A"],
["Donne le trio correspondant à Georges Barbier.",0,null,"Verbeau + terrains de football et basket"],
["Quel trio est correct ?",1,["Camp d'Attila / Stade Mermoz / athlétisme","Camp d'Attila / Aquacité / natation","Camp d'Attila / Cité Glace / patinage","Camp d'Attila / CNAC / cirque"],"A"],
["Quel équipement sportif est associé à la rue du Camp d'Attila ?",0,null,"Stade Mermoz"],
["Tu dois envoyer quelqu'un vers le tennis de table. Quelle indication est la plus précise ?",1,["Salle Cité Tirlet, rue de la Charrière","Stade Mermoz, rue du Camp d'Attila","Grand Jard, avenue du Général Leclerc","Aquacité"],"A"],
["Quelle rue dois-tu donner à quelqu'un qui cherche la Salle Cité Tirlet ?",0,null,"Rue de la Charrière"],
["Quel couple lieu/rue est correct ?",1,["Gymnase Pierre Curie / rue Oradour","Gymnase Kiezer / rue Oradour","Cité Tirlet / rue Oradour","Prieur de la Marne / rue Oradour"],"A"],
["Quel gymnase se trouve rue Oradour ?",0,null,"Gymnase Pierre Curie"],
["Quel couple est correct ?",1,["Prieur de la Marne / rue du Grenier à Sel","Pierre Curie / rue du Grenier à Sel","Kiezer / rue du Grenier à Sel","Nicolas Appert / rue du Grenier à Sel"],"A"],
["Quel gymnase est rue du Grenier à Sel ?",0,null,"Gymnase Prieur de la Marne"],
["Quel couple est correct ?",1,["Dojo Trussonnerie / rue Leconte de l'Isle","Cité Tirlet / rue Leconte de l'Isle","Kiezer / rue Leconte de l'Isle","Pierre Curie / rue Leconte de l'Isle"],"A"],
["Quelle activité est associée au dojo de la Trussonnerie dans le programme ?",0,null,"Danse Hip-Hop"],
["Quel couple est correct ?",1,["Nicolas Appert / cirque","Nicolas Appert / tennis de table","Nicolas Appert / patinage","Nicolas Appert / natation"],"A"],
["Quel équipement associes-tu à l'activité cirque en complément du CNAC ?",0,null,"Gymnase Nicolas Appert"],
["Quel lieu est le plus logique si tu veux passer du tennis à la danse Hip-Hop ?",1,["René Saché puis dojo de la Trussonnerie","Cité Glace puis Aquacité","Grand Jard puis Préfecture","Gare puis Cathédrale"],"A"],
["Donne un itinéraire de deux équipements permettant de pratiquer deux sports différents, sans utiliser les mêmes installations.",0,null,"libre"],
["Quel lieu est le plus directement lié à la Foire de Châlons ?",1,["Capitole","Petit Jard","Cité Glace","Préfecture"],"A"],
["Quel grand événement de fin août/début septembre 2026 doit connaître un joueur qui suit l'actualité locale ?",0,null,"libre"],
["En août 2026, quel événement se déroule au Grand Jard ?",1,["Châlons Plage","Foire de Châlons","War on Screen","European Tattoo Show"],"A"],
["Quel événement est annoncé du 28 août au 7 septembre 2026 ?",0,null,"80e Foire de Châlons"],
["Quel événement est prévu en octobre 2026 ?",1,["War on Screen","Châlons Plage","Foire de Châlons","Les Jeudis de Châlons"],"A"],
["Dans quel mois a lieu War on Screen 2026 ?",0,null,"Octobre"],
["Quel événement est prévu les 19 et 20 septembre 2026 ?",1,["Internationaux de France d'Échecs","Foire de Châlons","Châlons Plage","War on Screen"],"A"],
["Quel festival est prévu du 11 au 27 septembre 2026 ?",0,null,"Festival Itinéraires"],
["Quel événement est prévu les 16–18 octobre 2026 ?",1,["European Tattoo Show","Foire de Châlons","Châlons Plage","Internationaux d'échecs"],"A"],
["Quel événement sportif international est annoncé les 19–20 septembre 2026 ?",0,null,"Internationaux de France d'Échecs"],
["Quel événement est directement lié à la Foire mais possède une programmation musicale ?",1,["Foire en Scène","War on Screen","Festival Itinéraires","Châlons Plage"],"A"],
["Quel lieu culturel peut servir de repère à quelqu'un cherchant des spectacles contemporains ?",0,null,"La Comète"],
["Quel ensemble forme une combinaison logique transport + culture + espace vert ?",1,["Gare + Comète + Grand Jard","Cité Glace + Aquacité + Pont Vert","Préfecture + Tribunal + Mairie","Stade + gymnase + piscine"],"A"],
["Donne une combinaison de trois lieux permettant de montrer trois facettes différentes de Châlons.",0,null,"libre"],
["Tu dois montrer à un nouveau joueur administration + transport + loisirs. Quel trio est cohérent ?",1,["Préfecture + gare + Grand Jard","Stade + gymnase + terrain","Cathédrale + église + musée","Trois écoles"],"A"],
["Cite un lieu administratif, un lieu sportif et un lieu culturel de Châlons.",0,null,"libre"],
["Tu dois montrer quartier + sport + rue. Quel exemple est entièrement correct ?",1,["Verbeau + football/basket + Georges Barbier","Schmit + patinage + J.S. Bach","Bidée + natation + Branly","Mont-Héry + tennis de table + Oradour"],"A"],
["Donne un exemple complet quartier + rue + équipement sportif.",0,null,"libre"],
["Quel exemple montre une vraie connaissance de la géographie locale plutôt qu'une simple connaissance touristique ?",1,["Savoir relier une rue à un quartier et à son équipement","Connaître le nom de la ville","Connaître la cathédrale","Savoir que Châlons est en France"],"A"],
["Donne deux exemples de rue → quartier → équipement sans reprendre l'exemple de Georges Barbier.",0,null,"libre"],
["Quel niveau de connaissance commence à être nécessaire pour réussir les questions 350+ ?",1,["Connaître les lieux et leur localisation","Connaître uniquement l'histoire","Connaître les célébrités françaises","Connaître les départements français"],"A"],
["Tu es considéré comme quelqu'un qui connaît déjà correctement Châlons. Cite 10 lieux différents, répartis dans au moins 5 catégories : transports, services publics, sport, culture, espaces verts, éducation, loisirs, etc.",0,null,"libre"],
["Quel lieu associes-tu directement au réseau de transport urbain de Châlons ?",1,["SITAC","CNAC","CIAP","Capitole"],"A"],
["Quel est le nom du réseau de bus de Châlons-en-Champagne ?",0,null,"SITAC"],
["Quel lieu est principalement destiné aux trains ?",1,["Gare de Châlons-en-Champagne","Capitole","La Comète","Aquacité"],"A"],
["Si quelqu'un te dit je suis à la gare, quel moyen de transport est immédiatement identifiable ?",0,null,"Le train"],
["Quel bâtiment est le siège de la municipalité ?",1,["Hôtel de Ville","Préfecture","Tribunal","Sous-préfecture"],"A"],
["Sur quelle place se trouve l'Hôtel de Ville ?",0,null,"Place Foch"],
["Quelle place est associée à la Maison des syndicats Jean Reyssier ?",1,["Place de Verdun","Place Foch","Place Monseigneur Tissier","Place de la République"],"A"],
["Quel bâtiment administratif peux-tu associer à la place de Verdun ?",0,null,"Maison des syndicats Jean Reyssier"],
["Quel bâtiment est le siège des services de l'État au niveau départemental ?",1,["Préfecture","Mairie","Gare","Médiathèque"],"A"],
["Quel département a sa préfecture à Châlons-en-Champagne ?",0,null,"La Marne"],
["Quel monument est un des principaux repères du centre-ville ?",1,["Cathédrale Saint-Étienne","Stade Mermoz","Aquacité","Capitole"],"A"],
["Cite deux édifices religieux majeurs visibles dans le centre de Châlons.",0,null,"Cathédrale Saint-Étienne et Notre-Dame-en-Vaux"],
["Quel bâtiment religieux est particulièrement associé aux vitraux et au centre historique ?",1,["Notre-Dame-en-Vaux","Aquacité","Cité Glace","Capitole"],"A"],
["Quel édifice religieux est situé dans le centre historique et fait partie des grands repères de la ville ?",0,null,"Notre-Dame-en-Vaux"],
["Quel lieu culturel est consacré au dessin et à l'univers de Cabu ?",1,["Duduchothèque","CIAP","Musée Garinet","La Comète"],"A"],
["Qui est Cabu ?",0,null,"libre"],
["Quel lieu est consacré à l'interprétation de l'architecture et du patrimoine de Châlons ?",1,["CIAP","Aquacité","Capitole","Cité Glace"],"A"],
["Que signifie CIAP ?",0,null,"Centre d'Interprétation de l'Architecture et du Patrimoine"],
["Quel établissement est consacré notamment aux beaux-arts et à l'archéologie ?",1,["Musée des Beaux-Arts et d'Archéologie","Duduchothèque","La Comète","CNAC"],"A"],
["Cite un musée de Châlons autre que le musée des Beaux-Arts.",0,null,"Musée Garinet"],
["Quel lieu est directement associé au spectacle vivant ?",1,["La Comète","Préfecture","Gare","Grand Jard"],"A"],
["Quel type de lieu est La Comète ?",0,null,"Scène nationale / lieu culturel et de spectacle"],
["Quel établissement est spécialisé dans les arts du cirque ?",1,["CNAC","SITAC","CIAP","Capitole"],"A"],
["Que signifie CNAC ?",0,null,"Centre National des Arts du Cirque"],
["Quel lieu est dédié à la glace ?",1,["Cité Glace","Aquacité","Stade Mermoz","Pont Vert"],"A"],
["Quel équipement utiliserais-tu pour du patinage ?",0,null,"Cité Glace"],
["Quel équipement utiliserais-tu pour une activité aquatique ?",1,["Aquacité","Cité Glace","CNAC","Stade Mermoz"],"A"],
["Quel équipement associes-tu à la natation à Châlons ?",0,null,"Aquacité"],
["Quel lieu est principalement utilisé pour les grandes manifestations et salons ?",1,["Capitole en Champagne","Petit Jard","Cité Glace","CIAP"],"A"],
["Quel grand événement commercial annuel est associé au Capitole ?",0,null,"Foire de Châlons"],