["Tu veux faire de l'athlétisme. Où vas-tu ?",1,["Stade Mermoz","Grand Jard","Aire des Grévières","Verbeau"],"A"],
["Tu veux faire du basket à Mont-Saint-Michel : quel équipement cherches-tu ?",0,null,"Le terrain de basket"],
["Tu veux jouer au football à Verbeau. Quelle rue dois-tu connaître ?",1,["Rue Georges Barbier","Rue Branly","Rue J.S. Bach","Rue J.B. Drouet"],"A"],
["Tu veux trouver le terrain multisports de Schmit. Dans quelle rue dois-tu aller ?",0,null,"Rue Branly"],
["Tu cherches un terrain multisports à Vallée-Saint-Pierre. Où vas-tu ?",1,["Rue J.S. Bach","Rue Georges Barbier","Rue du Camp d'Attila","Avenue Croix-Dampierre"],"A"],
["Tu veux trouver l'équipement sportif de Mont-Héry. Quelle rue cherches-tu ?",0,null,"Rue J.B. Drouet"],
["Tu cherches plusieurs sports au même endroit, dont tennis et bicross. Quel site est le plus logique ?",1,["Pont Vert","Grand Jard","Mont-Saint-Michel","Bidée"],"A"],
["Quel équipement permet de pratiquer plusieurs sports au Pont Vert ?",0,null,"libre"],
["Tu cherches une activité de glisse sur roues. Où vas-tu ?",1,["Skatepark du Grand Jard","Aquacité","Cité Glace","La Comète"],"A"],
["Tu veux aller à la piscine : quel est le nom de l'équipement principal de Châlons ?",0,null,"Aquacité"],
["Tu veux faire du patinage. Où vas-tu ?",1,["Cité Glace","Aquacité","La Comète","Grand Jard"],"A"],
["Tu veux voir un spectacle : quel lieu dois-tu connaître ?",0,null,"La Comète"],
["Tu veux découvrir les arts du cirque. Quel lieu est le plus évident ?",1,["CNAC","SITAC","Aquacité","Cité Glace"],"A"],
["Quel réseau utilises-tu si tu veux prendre un bus à Châlons ?",0,null,"SITAC"],
["Tu veux prendre un train. Où vas-tu ?",1,["Gare de Châlons-en-Champagne","Grand Jard","La Comète","Préfecture"],"A"],
["Quel bâtiment administratif représente l'État dans le département ?",0,null,"La préfecture"],
["Tu dois te rendre à la mairie pour une démarche. Quel bâtiment cherches-tu ?",1,["Hôtel de Ville","Préfecture","Tribunal","Gare"],"A"],
["Quel bâtiment religieux dois-tu connaître si tu veux retrouver la cathédrale ?",0,null,"Saint-Étienne"],
["Tu cherches Notre-Dame-en-Vaux. Quel type de bâtiment est-ce ?",1,["Une collégiale","Une mairie","Une école","Une gare"],"A"],
["Quel monument est particulièrement reconnaissable grâce à son carillon ?",0,null,"Notre-Dame-en-Vaux"],
["Tu cherches un espace vert avec un kiosque à musique. Où vas-tu ?",1,["Grand Jard","Verbeau","Schmit","Mont-Héry"],"A"],
["Quel Jard est relié au Grand Jard par une passerelle ?",0,null,"Le Jard anglais"],
["Tu cherches l'arboretum. Quel Jard dois-tu visiter ?",1,["Petit Jard","Grand Jard","Jard anglais","Aucun"],"A"],
["Quel lieu est particulièrement adapté à une promenade en famille ?",0,null,"Les Jards"],
["Tu veux pratiquer une activité nautique pendant Châlons Plage. Où te rends-tu ?",1,["Grand Jard","Stade Mermoz","Verbeau","Cité Glace"],"A"],
["Cite deux activités que l'on peut retrouver à Châlons Plage.",0,null,"libre"],
["Quel lieu est associé au FabLab de la Ville ?",1,["OctoLab","Aquacité","CNAC","Cité Glace"],"A"],
["Quel lieu est associé aux collections des musées municipaux ?",0,null,"libre"],
["Quel lieu est associé à Cabu ?",1,["Duduchothèque","La Comète","Capitole","Aquacité"],"A"],
["Quel lieu permet de découvrir l'architecture et le patrimoine de Châlons ?",0,null,"Le CIAP"],
["Tu veux faire une sortie nature dans l'agglomération. Quel lieu peut être choisi ?",1,["Domaine de Coolus","Gare","Préfecture","Tribunal"],"A"],
["Quel lieu naturel peut-on visiter dans l'agglomération châlonnaise ?",0,null,"Le Domaine de Coolus"],
["Tu cherches un endroit pour un grand salon ou événement. Quel lieu correspond le mieux ?",1,["Capitole en Champagne","Petit Jard","Cathédrale","Gare"],"A"],
["Quel équipement est situé avenue du Maréchal Leclerc et associé aux arts du cirque à partir de septembre 2026 ?",0,null,"La Marnaise"],
["La Marnaise est principalement associée à :",1,["Les arts du cirque","La natation","Le patinage","Le football"],"A"],
["Quel équipement accueille notamment les activités de l'association de gymnastique L'Espoir – section cirque ?",0,null,"Gymnase Nicolas Appert"],
["Tu veux faire du badminton dans le cadre des activités sportives proposées en 2026. Quel gymnase est cité ?",1,["Gymnase Kiezer","Gymnase Nicolas Appert","Gymnase Prieur de la Marne","Gymnase Pierre Curie"],"A"],
["Dans quelle avenue se trouve le complexe sportif René Saché ?",0,null,"Avenue des Alliés"],
["Quel gymnase est cité pour le foot en salle dans les activités 2026 ?",1,["Gymnase Pierre Curie","Gymnase Kiezer","Gymnase René Saché","Gymnase Nicolas Appert"],"A"],
["Dans quelle rue se trouve le gymnase Pierre Curie ?",0,null,"Rue Oradour"],
["Quel lieu est utilisé pour le théâtre dans le programme d'activités 2026 ?",1,["Maison des syndicats Jean Reyssier","Grand Jard","Aquacité","Cité Glace"],"A"],
["Sur quelle place se trouve la Maison des syndicats Jean Reyssier ?",0,null,"Place de Verdun"],
["Quel lieu accueille notamment des activités de danse classique/contemporaine ?",1,["Gymnase Prieur de la Marne","Stade Mermoz","Cité Glace","Pont Vert"],"A"],
["Quelle rue correspond au gymnase Prieur de la Marne ?",0,null,"Rue du Grenier à Sel"],
["Quel équipement est cité pour le tennis dans les activités 2026 ?",1,["Terrains intérieurs et extérieurs, 150 avenue des Alliés","Grand Jard uniquement","Stade Mermoz","Aire des Grévières"],"A"],
["Quel équipement est utilisé pour le tennis de table dans le programme 2026 ?",0,null,"Salle Cité Tirlet"],
["Dans quelle rue se trouve la Salle Cité Tirlet ?",1,["Rue de la Charrière","Rue Branly","Rue Oradour","Rue J.B. Drouet"],"A"],
["Quel lieu est utilisé pour la danse Hip-Hop dans le programme 2026 ?",0,null,"Dojo de la Trussonnerie / Croix Jean Robert"],
["Dans quelle rue se trouve le dojo cité pour la danse Hip-Hop ?",1,["Rue Leconte de l'Isle","Rue de la Charrière","Rue Oradour","Rue du Grenier à Sel"],"A"],
["Tu dois faire découvrir Châlons à quelqu'un qui ne connaît absolument pas la ville : donne 5 lieux différents à lui faire découvrir, en essayant de mélanger centre-ville, loisirs, espaces verts, culture et transports.",0,null,"libre"],
["Tu cherches un terrain de football dans le secteur Verbeau. Quelle rue dois-tu connaître ?",1,["Rue Georges Barbier","Rue Branly","Rue J.S. Bach","Rue de la Charrière"],"A"],
["Cite deux équipements sportifs situés dans des quartiers différents de Châlons.",0,null,"libre"],
["Tu es rue Branly. Quel équipement sportif peux-tu trouver à cet endroit ?",1,["Terrain multisports","Stade Mermoz","Skatepark","Piscine"],"A"],
["Dans quel quartier se trouve la rue Branly utilisée pour l'équipement sportif ?",0,null,"Schmit"],
["Tu veux rejoindre le terrain multisports de Vallée-Saint-Pierre. Quelle rue recherches-tu ?",1,["J.S. Bach","Georges Barbier","Branly","Oradour"],"A"],
["Quel quartier associes-tu à la rue J.S. Bach dans le domaine sportif ?",0,null,"Vallée-Saint-Pierre"],
["Le terrain de football du secteur Verbeau se trouve rue :",1,["Georges Barbier","J.B. Drouet","Leconte de l'Isle","Oradour"],"A"],
["Quel équipement sportif se trouve rue du Camp d'Attila ?",0,null,"Stade Mermoz"],
["Quel équipement est particulièrement adapté à l'athlétisme ?",1,["Stade Mermoz","Grand Jard","Pont Vert","Mont-Saint-Michel"],"A"],
["Donne deux sports que l'on peut pratiquer au Pont Vert.",0,null,"libre"],
["Quel site possède également une piste de bicross ?",1,["Pont Vert","Verbeau","Grand Jard","Mont-Héry"],"A"],
["Quel site sportif associes-tu aux allées de Forêts ?",0,null,"Pont Vert"],
["Quel équipement se trouve avenue Croix-Dampierre ?",1,["Aire des Grévières","Stade Mermoz","Aquacité","Cité Glace"],"A"],
["Cite les deux sports principaux proposés à l'Aire des Grévières.",0,null,"Basket et football"],
["Tu cherches un terrain multisports avenue Pierre Semard. Quel lieu cherches-tu ?",1,["Espace Pierre Semard","Pont Vert","Grand Jard","Stade Mermoz"],"A"],
["Quel type d'équipement est l'Espace Pierre Semard ?",0,null,"Terrain multisports"],
["Quel équipement sportif se trouve au Mont-Saint-Michel ?",1,["Terrain de basket","Terrain de tennis","Piscine","Piste d'athlétisme"],"A"],
["Quel équipement trouve-t-on rue J.B. Drouet ?",0,null,"Terrains de basket et terrain de football synthétique"],
["Quel quartier associes-tu à la rue J.B. Drouet dans les équipements sportifs ?",1,["Mont-Héry","Schmit","Verbeau","Bidée"],"A"],
["Cite un équipement sportif situé dans le quartier de la Bidée.",0,null,"libre"],
["Quel équipement est situé au Grand Jard ?",1,["Terrain de football et skatepark à proximité","Piscine municipale","Patinoire","Gymnase uniquement"],"A"],
["Quel grand espace vert est directement associé à Châlons Plage ?",0,null,"Grand Jard"],
["Tu veux faire du skate dans un espace prévu pour cela. Où vas-tu ?",1,["Skatepark du Grand Jard","Petit Jard","Pont Vert","Stade Mermoz"],"A"],
["Quel espace vert est particulièrement associé à l'arboretum ?",0,null,"Petit Jard"],
["Quel Jard est relié au Grand Jard par une passerelle ?",1,["Jard anglais","Petit Jard","Jard Foch","Aucun"],"A"],
["Quel est le nom du troisième Jard en dehors du Grand et du Petit Jard ?",0,null,"Jard anglais"],
["Lequel de ces lieux se trouve dans le centre-ville ?",1,["Cathédrale Saint-Étienne","Pont Vert","Aire des Grévières uniquement","Domaine de Coolus"],"A"],
["Cite deux bâtiments religieux facilement identifiables dans le centre de Châlons.",0,null,"Cathédrale Saint-Étienne et Notre-Dame-en-Vaux"],
["Quelle place est directement associée à l'Hôtel de Ville ?",1,["Place Foch","Place de Verdun","Place Monseigneur Tissier","Place de Champagne"],"A"],
["Quel bâtiment administratif trouves-tu place Foch ?",0,null,"Hôtel de Ville"],
["Quel bâtiment administratif trouve-t-on place de Verdun ?",1,["Maison des syndicats Jean Reyssier","Hôtel de Ville","Préfecture","Tribunal"],"A"],
["Quelle place associes-tu à la Maison des syndicats Jean Reyssier ?",0,null,"Place de Verdun"],
["Quel bâtiment représente l'État au niveau départemental ?",1,["Préfecture","Mairie","Gare","Médiathèque"],"A"],
["Dans quelle ville se trouve la préfecture de la Marne ?",0,null,"Châlons-en-Champagne"],
["Quel lieu est principalement dédié aux spectacles vivants ?",1,["La Comète","Aquacité","Capitole","Gare"],"A"],
["Quel lieu associes-tu au cinéma et au festival War on Screen ?",0,null,"La Comète"],
["Quel lieu est particulièrement associé au cirque contemporain ?",1,["CNAC","SITAC","CIAP","Cité Glace"],"A"],
["Quel est le nom complet du CNAC ?",0,null,"Centre National des Arts du Cirque"],
["Quel équipement est dédié aux sports de glace ?",1,["Cité Glace","Aquacité","CNAC","Grand Jard"],"A"],
["Quel équipement est dédié aux activités aquatiques ?",0,null,"Aquacité"],
["Quel équipement peut accueillir une foire importante de la ville ?",1,["Capitole en Champagne","Petit Jard","La Comète uniquement","Stade Mermoz"],"A"],
["Quel grand événement annuel se déroule notamment au Capitole ?",0,null,"Foire de Châlons"],
["En 2026, quelle édition de la Foire de Châlons est annoncée ?",1,["80e","50e","100e","75e"],"A"],
["En 2026, à quelle période se déroule la Foire de Châlons annoncée sur l'agenda municipal ?",0,null,"Du 28 août au 7 septembre 2026"],
["Quel événement musical est associé à la Foire de Châlons ?",1,["Foire en Scène","Châlons Plage","War on Screen","Les Jeudis du Parc"],"A"],
["Quel événement est consacré au cinéma international à Châlons ?",0,null,"War on Screen"],
["Quel lieu est associé à Cabu ?",1,["Duduchothèque","CIAP","Capitole","CNAC"],"A"],
["Quel est le vrai nom de Cabu ?",0,null,"Jean Cabut"],
["Quel équipement permet de consulter des livres, médias et ressources numériques ?",1,["Médiathèque","Préfecture","Tribunal","Stade"],"A"],
["Quel nom porte la grande médiathèque de Châlons ?",0,null,"Médiathèque Pompidou"],
["Tu pars du centre-ville et tu veux aller à la gare : quel type de déplacement est logique ?",1,["Marcher, vélo, bus ou voiture","Prendre un bateau obligatoire","Prendre l'autoroute","Aller à Reims d'abord"],"A"],
["Cite deux moyens de transport permettant de circuler dans Châlons sans utiliser ta voiture.",0,null,"libre"],
["Quel réseau dois-tu consulter pour connaître les lignes de bus ?",1,["SITAC","SNCF uniquement","CNAC","CIAP"],"A"],
["Quel type de transport dessert les différents quartiers de Châlons avec le réseau SITAC ?",0,null,"Les bus"],
["Tu veux connaître les établissements scolaires de Châlons. Quelle ressource municipale peut les localiser ?",1,["L'annuaire des établissements scolaires","Le programme de la Foire","Le plan du Grand Jard","Le calendrier de la Comète"],"A"],
["Combien de collèges sont actuellement listés dans l'annuaire municipal autour de Châlons ?",0,null,"5"],
["Combien de lycées sont actuellement listés dans cet annuaire ?",1,["7","3","12","15"],"A"],
["Combien d'établissements maternelle et élémentaire sont listés dans l'annuaire ?",0,null,"9"],
["Quel type de service n'est PAS une catégorie de l'annuaire municipal cité ?",1,["Justice","Santé","Police-Gendarmerie","Aéroport international"],"D"],
["Combien de lieux sont actuellement recensés dans la catégorie Justice de l'annuaire ?",0,null,"13"],
["Combien de lieux sont recensés dans la catégorie Police-Gendarmerie ?",1,["3","8","13","1"],"A"],
["Combien de lieux sont recensés dans la catégorie Santé ?",0,null,"2"],
["Quelle catégorie possède 11 lieux dans l'annuaire ?",1,["Social","Mairie","Santé","Territoire"],"A"],
["Combien de lieux sont recensés dans la catégorie Social ?",0,null,"11"],
["Quelle catégorie possède 7 lieux ?",1,["Économie","Mairie","Territoire","Santé"],"A"],
["Combien de lieux sont recensés dans la catégorie Collectivité ?",0,null,"3"],
["Quelle catégorie possède seulement un lieu dans l'annuaire ?",1,["Mairie","Justice","Social","Formation"],"A"],
["Quelle catégorie possède 11 lieux en plus de la catégorie Social ?",0,null,"Formation"],
["Quel lieu est le plus logique pour une démarche municipale ?",1,["Hôtel de Ville","Cité Glace","Aquacité","Grand Jard"],"A"],
["Quel bâtiment chercherais-tu pour une démarche relevant de l'État plutôt que de la commune ?",0,null,"Préfecture"],
["Quel lieu est le plus logique pour une exposition municipale ?",1,["Un musée","Un stade","Une station-service","Une gare"],"A"],
["Cite un lieu culturel de Châlons autre que la Comète.",0,null,"libre"],
["Quel lieu est le plus logique pour un concert ou spectacle ?",1,["La Comète","La préfecture","Le tribunal","Le commissariat"],"A"],
["Quel lieu est le plus logique pour une compétition de patinage ?",0,null,"Cité Glace"],
["Quel lieu est le plus logique pour une compétition de natation ?",1,["Aquacité","Cité Glace","La Comète","Petit Jard"],"A"],
["Quel lieu est le plus logique pour une activité de cirque ?",0,null,"CNAC"],
["Tu veux assister à une foire commerciale : où te rends-tu ?",1,["Capitole en Champagne","Petit Jard","Cathédrale","Stade Mermoz"],"A"],
["Quel lieu associes-tu aux grands événements commerciaux de Châlons ?",0,null,"Capitole en Champagne"],
["Tu veux faire une promenade arborée avec des espèces variées. Quel endroit choisir ?",1,["Petit Jard","Gare","Verbeau","Zone industrielle"],"A"],
["Quel Jard est particulièrement intéressant pour observer des arbres et arbustes variés ?",0,null,"Petit Jard"],
["Tu veux faire une activité nautique en été. Quel lieu est le plus logique ?",1,["Grand Jard / Châlons Plage","Stade Mermoz","Cité Glace","Préfecture"],"A"],
["Quel événement est proposé en août 2026 avec des animations nautiques ?",0,null,"Châlons Plage"],
["Quelle activité touristique permet de découvrir Châlons sur l'eau ?",1,["Balade en barque Métamorph'eau'ses","Bus SITAC","Foire de Châlons","War on Screen"],"A"],
["Quel nom porte le service/activité de balade en barque touristique ?",0,null,"Métamorph'eau'ses"],
["Tu veux rejoindre un événement à pied depuis un autre quartier : quelle information est la plus importante ?",1,["La localisation des deux lieux","La date de naissance du maire","L'histoire de la ville","Le nombre de musées en 1900"],"A"],
["Donne trois informations utiles pour préparer un trajet dans Châlons.",0,null,"libre"],
["Pour rejoindre rapidement un lieu en transport collectif, qu'est-ce qui compte le plus ?",1,["Ligne, arrêt et direction","Nom du quartier uniquement","La météo uniquement","La superficie de la ville"],"A"],
["Quelles sont les trois informations de base à vérifier sur un bus avant de monter ?",0,null,"libre"],
["Tu es perdu dans Châlons. Quel élément urbain est généralement le plus utile pour te repérer ?",1,["Nom de rue / panneau / point remarquable","La couleur d'une voiture","Le nombre de nuages","La marque des lampadaires"],"A"],
["Cite trois repères que tu pourrais utiliser pour te localiser dans Châlons.",0,null,"libre"],
["Quel bâtiment est un excellent repère pour identifier le centre historique ?",1,["Cathédrale Saint-Étienne","Aquacité","Pont Vert","Capitole"],"A"],
["Cite deux monuments qui peuvent servir de repères dans le centre.",0,null,"libre"],
["Quel lieu est particulièrement utile comme repère pour les transports ferroviaires ?",1,["Gare","Grand Jard","Comète","CIAP"],"A"],
["Quel lieu est naturellement associé aux trains ?",0,null,"libre"],
["Quel lieu est naturellement associé aux bus ?",1,["Arrêt SITAC","Cathédrale","Musée","Stade"],"A"],
["Quel réseau dois-tu connaître si ton personnage utilise les bus ?",0,null,"SITAC"],
["Quel lieu est un repère administratif majeur ?",1,["Préfecture","Petit Jard","Cité Glace","Aquacité"],"A"],
["Quel lieu est un repère administratif municipal majeur ?",0,null,"Hôtel de Ville"],
["Quel lieu est un repère culturel majeur ?",1,["La Comète","Stade Mermoz","Pont Vert","Aire des Grévières"],"A"],
["Cite cinq repères urbains différents que tu pourrais donner à quelqu'un pour lui expliquer où tu te trouves dans Châlons.",0,null,"libre"],
