["Dans quel secteur associes-tu la rue Georges Barbier ?",1,["Verbeau","Schmit","Mont-Héry","Vallée-Saint-Pierre"],"A"],
["Quel équipement sportif peux-tu trouver rue Georges Barbier ?",0,null,"Terrains de football et de basket"],
["Rue Branly correspond notamment à quel secteur ?",1,["Schmit","Verbeau","Bidée","Mont-Héry"],"A"],
["Quel équipement trouve-t-on rue Branly ?",0,null,"Terrain multisports"],
["Rue J.S. Bach est associée à quel quartier ?",1,["Vallée-Saint-Pierre","Schmit","Verbeau","Bidée"],"A"],
["Quel équipement trouve-t-on rue J.S. Bach ?",0,null,"Terrain multisports"],
["Rue J.B. Drouet est associée à quel secteur ?",1,["Mont-Héry","Verbeau","Schmit","Vallée-Saint-Pierre"],"A"],
["Quel équipement trouve-t-on rue J.B. Drouet ?",0,null,"Terrains de basket et terrain de football synthétique"],
["Quel secteur associes-tu au terrain de football près du CSC Rive Gauche ?",1,["Bidée","Verbeau","Schmit","Mont-Héry"],"A"],
["Quel centre social est associé à la Bidée ?",0,null,"CSC Rive Gauche"],
["Quel centre social porte le nom du quartier Schmit ?",1,["CSC Émile Schmit","CSC Rive Gauche","CSC Verbeau","CSC Vallée-Saint-Pierre"],"A"],
["Quel quartier donne son nom au CSC Émile Schmit ?",0,null,"Schmit"],
["Quel équipement est associé à la rue du Camp d'Attila ?",1,["Stade Mermoz","Aquacité","Cité Glace","Pont Vert"],"A"],
["Quel grand équipement sportif est situé rue du Camp d'Attila ?",0,null,"Stade Mermoz"],
["Quel site est particulièrement intéressant pour pratiquer plusieurs sports de plein air ?",1,["Pont Vert","Préfecture","Gare","CIAP"],"A"],
["Cite quatre activités sportives possibles au Pont Vert.",0,null,"libre"],
["Quelle avenue accueille l'Aire des Grévières ?",1,["Avenue Croix-Dampierre","Avenue des Alliés","Avenue du Général Leclerc","Avenue de Paris"],"A"],
["Quels deux sports associes-tu à l'Aire des Grévières ?",0,null,"Basket et football"],
["Quelle avenue associes-tu au complexe sportif René Saché ?",1,["Avenue des Alliés","Avenue Croix-Dampierre","Avenue du Général Leclerc","Avenue de Champagne"],"A"],
["Quel équipement sportif porte le nom de René Saché ?",0,null,"Complexe sportif René Saché"],
["Quelle rue associes-tu au gymnase Pierre Curie ?",1,["Rue Oradour","Rue Branly","Rue de la Charrière","Rue Leconte de l'Isle"],"A"],
["Quel sport est associé au gymnase Pierre Curie ?",0,null,"Foot en salle"],
["Quelle rue associes-tu à la Salle Cité Tirlet ?",1,["Rue de la Charrière","Rue Oradour","Rue Branly","Rue J.S. Bach"],"A"],
["Quel sport est associé à la Salle Cité Tirlet ?",0,null,"Tennis de table"],
["Quel gymnase est associé à la rue du Grenier à Sel ?",1,["Prieur de la Marne","Pierre Curie","Kiezer","Nicolas Appert"],"A"],
["Quelle activité sportive associes-tu au gymnase Prieur de la Marne ?",0,null,"Danse"],
["Quelle rue associes-tu au dojo de la Trussonnerie ?",1,["Rue Leconte de l'Isle","Rue Oradour","Rue Branly","Rue du Grenier à Sel"],"A"],
["Quelle activité est associée au dojo de la Trussonnerie ?",0,null,"Danse Hip-Hop"],
["Quel équipement est associé à l'activité cirque ?",1,["Gymnase Nicolas Appert","Gymnase Pierre Curie","Salle Cité Tirlet","Kiezer"],"A"],
["Quel autre grand établissement châlonnais est consacré au cirque ?",0,null,"CNAC"],
["Lequel est correctement associé ?",1,["Aquacité → eau","Cité Glace → natation","CNAC → football","SITAC → patinage"],"A"],
["Lequel est correctement associé ?",1,["SITAC → bus","CNAC → trains","CIAP → bus","Capitole → piscine"],"A"],
["Lequel est correctement associé ?",1,["Capitole → Foire de Châlons","Cité Glace → Foire de Châlons","Aquacité → Foire de Châlons","Stade Mermoz → Foire de Châlons"],"A"],
["Quelle différence fais-tu entre SITAC et SNCF ?",0,null,"libre"],
["Tu cherches un lieu culturel, mais tu ne veux ni musée ni monument religieux. Que choisis-tu ?",1,["La Comète","Cathédrale Saint-Étienne","Notre-Dame-en-Vaux","Musée Garinet"],"A"],
["Tu cherches un musée mais pas un lieu de spectacle.",1,["Musée Garinet","La Comète","Capitole","CNAC"],"A"],
["Donne une différence entre le CIAP et un musée.",0,null,"libre"],
["Quel couple est faux ?",1,["Duduchothèque → Cabu","CNAC → cirque","Aquacité → glace","Cité Glace → patinage"],"C"],
["Quel couple est faux ?",1,["Pont Vert → bicross","Stade Mermoz → athlétisme","Aquacité → activités aquatiques","Cité Glace → tennis"],"D"],
["Cite deux équipements où l'on pratique des activités sportives totalement différentes.",0,null,"libre"],
["Quel itinéraire thématique est cohérent pour une journée culture ?",1,["Musée → Duduchothèque → La Comète","Aquacité → Cité Glace → Pont Vert","Stade → gymnase → terrain","Gare → dépôt → arrêt de bus"],"A"],
["Donne trois lieux culturels châlonnais différents.",0,null,"libre"],
["Quel itinéraire thématique est cohérent pour une journée sport ?",1,["Pont Vert → Aquacité → Cité Glace","Préfecture → mairie → tribunal","Musée → CIAP → Duduchothèque","Gare → mairie → cathédrale"],"A"],
["Donne quatre équipements sportifs différents à Châlons.",0,null,"libre"],
["Quel lieu est le moins pertinent pour une sortie sportive ?",1,["Préfecture","Pont Vert","Aquacité","Stade Mermoz"],"A"],
["Quel lieu est le moins pertinent pour prendre un bus urbain ?",1,["SITAC","Un arrêt de bus","Gare routière/arrêt desservi","Musée"],"D"],
["Quel est le meilleur repère pour quelqu'un qui cherche la mairie ?",0,null,"libre"],
["Quel lieu est le plus logique pour une démarche auprès de la commune ?",1,["Hôtel de Ville","Préfecture","Cité Glace","Capitole"],"A"],
["Quel lieu est le plus logique pour une démarche relevant des services de l'État ?",1,["Préfecture","Hôtel de Ville","Grand Jard","La Comète"],"A"],
["Quel est le piège entre mairie et préfecture ?",0,null,"libre"],
["Tu vois un panneau indiquant SITAC. Qu'est-ce qui doit immédiatement te venir à l'esprit ?",1,["Transport urbain","Sport","Culture","Justice"],"A"],
["Tu vois un bâtiment marqué Préfecture. Quelle institution attends-tu à l'intérieur ?",0,null,"libre"],
["Tu vois un bâtiment Hôtel de Ville. Dans quelle catégorie le classes-tu ?",1,["Administration municipale","Sport","Culture","Transport"],"A"],
["Tu vois une grande infrastructure avec des gradins et une piste sportive : quel équipement châlonnais pourrait correspondre ?",0,null,"Stade Mermoz"],
["Tu vois une infrastructure dédiée à la glace : laquelle ?",1,["Cité Glace","Aquacité","Pont Vert","René Saché"],"A"],
["Tu vois une grande piscine/centre aquatique : quel équipement cherches-tu ?",0,null,"Aquacité"],
["Tu vois un espace avec des terrains multisports en plein air. Quel type d'équipement est-ce ?",1,["Terrain multisports","Musée","Tribunal","Médiathèque"],"A"],
["Cite deux endroits où tu peux trouver un terrain multisports.",0,null,"libre"],
["Quel élément te permet le mieux de distinguer deux quartiers portant des équipements similaires ?",1,["La rue précise","La météo","La couleur du ciel","Le nombre de voitures"],"A"],
["Pourquoi connaître uniquement le nom d'un équipement n'est parfois pas suffisant pour se repérer ?",0,null,"libre"],
["Deux terrains portent la même fonction multisports. Quelle information permet de les différencier ?",1,["Leur localisation","Leur sport préféré","Leur couleur","Leur date de construction uniquement"],"A"],
["Donne les deux rues citées dans ce pack qui possèdent un terrain multisports.",0,null,"Rue Branly et rue J.S. Bach"],
["Quel duo quartier + rue est incorrect ?",1,["Verbeau + Georges Barbier","Schmit + Branly","Vallée-Saint-Pierre + J.S. Bach","Verbeau + J.B. Drouet"],"D"],
["Quel duo est incorrect ?",1,["Mont-Héry + J.B. Drouet","Verbeau + Georges Barbier","Schmit + Branly","Vallée-Saint-Pierre + Georges Barbier"],"D"],
["Donne une rue associée au quartier Verbeau.",0,null,"Georges Barbier"],
["Donne une rue associée au quartier Schmit.",0,null,"Branly"],
["Donne une rue associée à Vallée-Saint-Pierre.",0,null,"J.S. Bach"],
["Donne une rue associée à Mont-Héry.",0,null,"J.B. Drouet"],
["Quel ensemble contient quatre associations correctes ?",1,["Georges Barbier/Verbeau ; Branly/Schmit ; J.S. Bach/Vallée-Saint-Pierre ; J.B. Drouet/Mont-Héry","Georges Barbier/Schmit ; Branly/Verbeau ; J.S. Bach/Mont-Héry ; J.B. Drouet/Bidée","Toutes fausses","Une seule correcte"],"A"],
["Sans regarder les réponses précédentes, écris 4 rues + leurs quartiers correspondants.",0,null,"libre"],
["Tu cherches un terrain de football synthétique et tu sais que tu es à Mont-Héry. Où vas-tu ?",1,["J.B. Drouet","Georges Barbier","Branly","J.S. Bach"],"A"],
["Tu es à Schmit et cherches un terrain multisports. Donne la rue.",0,null,"Branly"],
["Tu es à Vallée-Saint-Pierre. Quelle rue dois-tu retenir pour un terrain multisports ?",1,["J.S. Bach","Branly","Georges Barbier","J.B. Drouet"],"A"],
["Tu es à Verbeau et cherches football + basket. Quelle rue ?",0,null,"Georges Barbier"],
["Tu es à la Bidée et quelqu'un te demande où se trouve le terrain de football proche du centre social. Que réponds-tu ?",1,["Près du CSC Rive Gauche","Près du CNAC","Près de l'Aquacité","Près du Capitole"],"A"],
["Quel centre social dois-tu connaître pour la Bidée ?",0,null,"CSC Rive Gauche"],
["Tu veux faire du basket mais tu es près de l'Aire des Grévières. Quelle activité peux-tu y trouver ?",1,["Basket","Patinage","Natation","Athlétisme"],"A"],
["Quel autre sport est associé à l'Aire des Grévières ?",0,null,"Football"],
["Tu veux du basket dans le secteur Mont-Saint-Michel. Quel équipement cherches-tu ?",1,["Terrain de basket","Cité Glace","Aquacité","Gymnase Kiezer"],"A"],
["Quel sport associes-tu au terrain du Mont-Saint-Michel ?",0,null,"Basket"],
["Tu cherches football + tennis + bicross.",1,["Pont Vert","Aire des Grévières","Mont-Saint-Michel","Georges Barbier"],"A"],
["Quel site possède une piste de bicross ?",0,null,"Pont Vert"],
["Quel équipement est le plus adapté à quelqu'un qui veut faire du badminton ?",1,["Gymnase Kiezer","Gymnase Pierre Curie","Cité Glace","Stade Mermoz"],"A"],
["Quel sport est associé au gymnase Kiezer ?",0,null,"Badminton"],
["Tu veux du foot en salle.",1,["Pierre Curie","Kiezer","Cité Tirlet","Nicolas Appert"],"A"],
["Quel gymnase est associé au foot en salle ?",0,null,"Pierre Curie"],
["Tu veux du tennis de table.",1,["Cité Tirlet","Pierre Curie","Kiezer","René Saché"],"A"],
["Dans quelle rue se trouve la Salle Cité Tirlet ?",0,null,"Rue de la Charrière"],
["Tu veux pratiquer la danse Hip-Hop.",1,["Dojo de la Trussonnerie","Stade Mermoz","Pierre Curie","Cité Glace"],"A"],
["Quelle rue dois-tu retenir pour le dojo de la Trussonnerie ?",0,null,"Rue Leconte de l'Isle"],
["Tu veux pratiquer la danse classique/contemporaine.",1,["Prieur de la Marne","Pierre Curie","Kiezer","Nicolas Appert"],"A"],
["Dans quelle rue se trouve le gymnase Prieur de la Marne ?",0,null,"Rue du Grenier à Sel"],
["Tu cherches une activité cirque dans un gymnase.",1,["Nicolas Appert","Kiezer","Pierre Curie","Prieur de la Marne"],"A"],
["Quel grand établissement spécialisé dans le cirque dois-tu également connaître ?",0,null,"CNAC"],
["Tu veux jouer au tennis en intérieur et extérieur.",1,["René Saché","Cité Tirlet","Pierre Curie","Pont Vert uniquement"],"A"],
["Sur quelle avenue se trouve le complexe René Saché ?",0,null,"Avenue des Alliés"],
["Quel lieu est le meilleur choix pour du tennis de table ?",1,["Salle Cité Tirlet","Pont Vert","Stade Mermoz","Grand Jard"],"A"],
["Quel lieu choisirais-tu pour du badminton ?",0,null,"Gymnase Kiezer"],
["Quel lieu choisirais-tu pour du foot en salle ?",1,["Gymnase Pierre Curie","Gymnase Kiezer","Salle Cité Tirlet","Dojo Trussonnerie"],"A"],
["Quel lieu choisirais-tu pour du Hip-Hop ?",0,null,"Dojo de la Trussonnerie"],
["Quel lieu choisirais-tu pour du cirque ?",1,["Gymnase Nicolas Appert / CNAC","Cité Glace","Aquacité","Stade Mermoz"],"A"],
["Quel lieu choisirais-tu pour du patinage ?",0,null,"Cité Glace"],
["Quel lieu choisirais-tu pour de la natation ?",1,["Aquacité","Cité Glace","CNAC","Pont Vert"],"A"],
["Quel lieu choisirais-tu pour de l'athlétisme ?",0,null,"Stade Mermoz"],
["Quel lieu choisirais-tu pour du bicross ?",1,["Pont Vert","Aquacité","Stade Mermoz","Cité Glace"],"A"],
["Quel lieu choisirais-tu pour du basket + football en plein air à l'Aire des Grévières ?",0,null,"Avenue Croix-Dampierre"],
["Quel lieu associe le mieux football + tennis + bicross ?",1,["Pont Vert","Stade Mermoz","Aire des Grévières","Mont-Saint-Michel"],"A"],
["Quel site possède plusieurs installations sportives différentes dans un même ensemble ?",0,null,"Pont Vert"],
["Quel lieu est le plus polyvalent parmi ces propositions ?",1,["Pont Vert","Cité Glace","Aquacité","Stade Mermoz"],"A"],
["Pourquoi le Pont Vert est-il particulièrement intéressant pour une question de connaissance locale ?",0,null,"libre"],
["Quelle association contient uniquement des lieux de Châlons liés au sport ?",1,["Aquacité / Cité Glace / Stade Mermoz","Préfecture / CIAP / Comète","Mairie / Gare / Cathédrale","Duduchothèque / Musée / CNAC"],"A"],
["Donne 5 équipements sportifs de Châlons sans utiliser Pont Vert.",0,null,"libre"],
["Quelle association contient uniquement des lieux culturels ?",1,["Duduchothèque / CIAP / La Comète","Aquacité / CNAC / Stade Mermoz","Gare / SITAC / mairie","Préfecture / tribunal / mairie"],"A"],
["Donne quatre lieux culturels de Châlons.",0,null,"libre"],
["Quelle association contient uniquement des lieux administratifs ?",1,["Hôtel de Ville / Préfecture / Maison des syndicats","Aquacité / mairie / Stade","Comète / CIAP / Préfecture","Gare / SITAC / Capitole"],"A"],
["Cite trois bâtiments/services administratifs de Châlons.",0,null,"libre"],
["Tu dois expliquer à quelqu'un la différence entre lieu et quartier. Laquelle est correcte ?",1,["Un quartier est une partie de la ville ; un lieu est un emplacement précis","Un quartier est toujours un bâtiment","Un lieu est toujours un quartier","Il n'y a aucune différence"],"A"],
["Donne un exemple de quartier + un exemple de lieu précis.",0,null,"libre"],
["Parmi ces réponses, laquelle contient un quartier et non un équipement ?",1,["Verbeau","Aquacité","Cité Glace","Stade Mermoz"],"A"],
["Parmi ces réponses, laquelle contient un équipement et non un quartier ?",1,["Aquacité","Verbeau","Schmit","Bidée"],"A"],
["Cite deux quartiers et deux équipements sportifs.",0,null,"libre"],
["Quel raisonnement est le plus utile si ton GPS tombe en panne ?",1,["Utiliser les rues, monuments, places et équipements connus","Deviner au hasard","Suivre n'importe quelle voiture","Revenir automatiquement à Paris"],"A"],
["Cite cinq éléments urbains pouvant servir de repères sans GPS.",0,null,"libre"],
["Tu vois Georges Barbier sur un panneau. Quel élément peux-tu déduire immédiatement ?",1,["Tu es potentiellement dans le secteur Verbeau","Tu es forcément à Schmit","Tu es à la gare","Tu es au Grand Jard"],"A"],
["Tu vois Branly. Quel secteur dois-tu envisager ?",1,["Schmit","Verbeau","Mont-Héry","Bidée"],"A"],
["Tu vois J.S. Bach. Quel secteur dois-tu envisager ?",1,["Vallée-Saint-Pierre","Schmit","Verbeau","Mont-Héry"],"A"],
["Tu vois J.B. Drouet. Quel secteur dois-tu envisager ?",1,["Mont-Héry","Bidée","Schmit","Verbeau"],"A"],
["Écris les quatre associations rue → quartier que tu dois absolument connaître pour réussir ce niveau.",0,null,"libre"],
["Quel groupe contient quatre sports différents du Pont Vert ?",1,["Football / tennis / basket / handball","Natation / patinage / cirque / danse","Athlétisme / natation / tennis de table / cirque","Golf / ski / rugby / hockey"],"A"],
["Cite cinq activités sportives possibles au Pont Vert.",0,null,"libre"],
["Quel équipement est le plus cohérent avec eau ?",1,["Aquacité","Cité Glace","CNAC","Mermoz"],"A"],
["Quel équipement est le plus cohérent avec glace ?",1,["Cité Glace","Aquacité","Pont Vert","René Saché"],"A"],
["Quel équipement est le plus cohérent avec cirque ?",1,["CNAC","Aquacité","SITAC","Cité Glace"],"A"],
["Quel équipement est le plus cohérent avec bus ?",1,["SITAC","CNAC","CIAP","CNAM"],"A"],
["Quel équipement est le plus cohérent avec foire ?",1,["Capitole","Cité Glace","Grand Jard","Musée Garinet"],"A"],
["Fais cinq associations lieu → fonction sans regarder les réponses précédentes.",0,null,"libre"],
["Tu dois faire découvrir Châlons à un nouveau joueur en 5 étapes. Quel parcours est le plus représentatif ?",1,["Centre historique → mairie → Grand Jard → équipement sportif → lieu culturel","Autoroute → zone industrielle → sortie de ville → retour","Uniquement trois parkings","Uniquement trois rues"],"A"],
["Construis ton propre parcours de découverte de Châlons en 5 lieux, avec une justification pour chacun.",0,null,"libre"],
["Quel joueur connaît réellement mieux la ville ?",1,["Celui qui sait relier quartiers, rues, équipements et transports","Celui qui connaît seulement la cathédrale","Celui qui connaît uniquement la mairie","Celui qui connaît seulement le nom du département"],"A"],
["Donne trois exemples montrant que tu connais Châlons autrement que par ses monuments.",0,null,"libre"],
["Tu es à Schmit, tu cherches un terrain multisports, puis tu veux aller faire du tennis. Quel premier lieu dois-tu identifier ?",1,["Rue Branly","Rue Georges Barbier","Rue J.S. Bach","Rue J.B. Drouet"],"A"],
["Tu es à Mont-Héry. Donne une rue + un équipement sportif correspondant.",0,null,"libre"],
["Tu es à Vallée-Saint-Pierre. Tu cherches un terrain multisports.",1,["J.S. Bach","Branly","Georges Barbier","J.B. Drouet"],"A"],
["Tu es à Verbeau. Donne une rue + les deux sports associés aux terrains cités.",0,null,"libre"],
["Quel joueur a donné une réponse complètement cohérente ?",1,["Je suis à Schmit, rue Branly, près du terrain multisports.","Je suis à Schmit, rue J.S. Bach, près de la piscine.","Je suis à Mont-Héry, rue Georges Barbier, à la patinoire.","Je suis à Verbeau, rue J.B. Drouet, au CNAC."],"A"],
["Donne une phrase du même type avec un autre quartier.",0,null,"libre"],
["Tu veux montrer à un joueur un lieu culturel, un lieu sportif et un espace vert. Quel trio est valide ?",1,["La Comète + Cité Glace + Grand Jard","Préfecture + mairie + tribunal","Gare + SITAC + arrêt","Trois rues"],"A"],
["Donne un autre trio culture + sport + espace vert.",0,null,"libre"],
["Tu veux montrer transport + administration + sport. Quel trio est valide ?",1,["Gare + Hôtel de Ville + Aquacité","CIAP + musée + Comète","Grand Jard + Petit Jard + Jard anglais","Trois quartiers"],"A"],
["Construis ton propre trio transport + administration + sport.",0,null,"libre"],
["Quel élément est le plus difficile à retenir pour un nouveau joueur ?",1,["Rue + quartier + équipement précis","Le nom de Châlons","Le département","La France"],"A"],
["Écris 5 associations rue → quartier → équipement de mémoire.",0,null,"libre"],
["Combien de niveaux d'information sont présents dans rue Georges Barbier → Verbeau → terrains de football/basket ?",1,["3","1","2","5"],"A"],
["Donne une association à trois niveaux différente de Georges Barbier.",0,null,"libre"],
["Quel est le meilleur indice lorsqu'on cherche un équipement dans une ville ?",1,["Son nom + sa rue","Sa couleur","La météo","La marque des voitures autour"],"A"],
["Pourquoi une rue est-elle souvent plus utile qu'un simple nom de quartier pour trouver un lieu ?",0,null,"libre"],
["Quel joueur possède la meilleure connaissance pratique de Châlons ?",1,["Celui qui sait expliquer comment aller d'un lieu à un autre","Celui qui connaît 50 dates historiques","Celui qui connaît uniquement les monuments","Celui qui connaît uniquement les quartiers"],"A"],
["Explique comment tu guiderais quelqu'un qui ne connaît absolument pas Châlons vers un équipement sportif.",0,null,"libre"],
["Quel type de question sera probablement le plus difficile dans les prochains packs ?",1,["Identifier un lieu à partir de plusieurs indices","Reconnaître le nom de la ville","Donner le département","Reconnaître le drapeau français"],"A"],
["Écris une question difficile sur Châlons qui pourrait être ajoutée au jeu.",0,null,"libre"],
["Dernier test : lequel de ces ensembles est entièrement cohérent ?",1,["Branly/Schmit/multisports ; J.S. Bach/Vallée-Saint-Pierre/multisports ; J.B. Drouet/Mont-Héry/football synthétique","Branly/Verbeau/piscine ; J.S. Bach/Schmit/patinoire ; J.B. Drouet/Bidée/CNAC","Georges Barbier/Mont-Héry/Aquacité ; Branly/Bidée/Stade Mermoz","Aucun"],"A"],
["Donne 3 associations complètes rue + quartier + équipement.",0,null,"libre"],
["Quel ensemble contient uniquement des espaces verts / lieux de promenade ?",1,["Grand Jard / Petit Jard / Jard anglais","Aquacité / Cité Glace / Pont Vert","Préfecture / mairie / gare","CNAC / Comète / CIAP"],"A"],
["Cite les trois Jards de Châlons.",0,null,"Grand Jard, Petit Jard et Jard anglais"],
["Quel lieu est associé à une passerelle reliant les espaces des Jards ?",1,["Jard anglais / Grand Jard","Cité Glace","Stade Mermoz","Capitole"],"A"],
["Quel espace vert est particulièrement connu pour son arboretum ?",0,null,"Petit Jard"],
["Quel lieu associes-tu à Châlons Plage ?",1,["Grand Jard","Petit Jard","Stade Mermoz","Capitole"],"A"],
["Quel type d'activités peut-on retrouver à Châlons Plage ?",0,null,"libre"],
["Un joueur affirme : Je connais Châlons parce que je connais la cathédrale, la mairie et la Foire. Est-ce suffisant pour réussir les questions de ce niveau ?",1,["Non, il faut aussi connaître rues, quartiers, équipements, transports et repères locaux","Oui, c'est largement suffisant","Oui, si on connaît Paris","Seulement s'il connaît l'histoire de France"],"A"],
["Sans aucune aide, écris 10 informations différentes sur Châlons-en-Champagne, avec obligatoirement : 2 rues, 2 quartiers, 2 équipements sportifs, 1 bâtiment public, 1 lieu culturel, 1 espace vert, 1 moyen de transport ou réseau.",0,null,"libre"],